# -*- Mode:python; indent-tabs-mode:nil; coding:utf-8 -*-

def build(ctx):
    sources = ['address.cc',
               'alarm.cc',
               'connection.cc',
               'dns_resolver.cc',
               'selectable.cc',
               'selector.cc',
               'selector_base.cc',
               'timeouter.cc',
               ]
    if not (ctx.env.ANDROID or ctx.env.IOS):
        sources.extend([
            # Removable (-50k)
            'selectable_filereader.cc',
            'udp_connection.cc',
            'ipclassifier.cc',
            ])
    ctx.add_lib(ctx,
        toplib = 'core',
        name = 'whisperlib.net',
        target = 'whisperlib',
        source = sources)

    ctx.install_all_includes(ctx)

    ctx.add_whisper_tests(ctx, [
            'address_test.cc',
            'dns_resolver_test.cc',
            'selector_test.cc',
            'selectable_filereader_test.cc',
            'udp_connection_test.cc',
            ])
