# -*- Mode:python; indent-tabs-mode:nil; coding:utf-8 -*-

def build(ctx):
    sources = [
        'logio.cc',
        'recordio.cc',
    ]
    ctx.add_lib(ctx,
        toplib = 'whisperlib',
        name = 'whisperlib.io.logio',
        target = 'whisperlib',
        source = sources)
    ctx.add_whisper_tests(ctx, [
            'logio_analyzer.cc',
            'logio_test.cc',
            'recordio_test.cc'
            ])
