// Copyright (c) 2009, Whispersoft s.r.l.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
// * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
// * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
// * Neither the name of Whispersoft s.r.l. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//

#ifndef __WHISPERLIB_BASE_CALLBACK_CALLBACK2_H__
#define __WHISPERLIB_BASE_CALLBACK_CALLBACK2_H__

#include "whisperlib/base/callback/callback.h"

namespace whisper {

template<typename X0, typename X1>
class Callback2 : public Callback {
public:
  Callback2(bool is_permanent)
    : Callback(),
      is_permanent_(is_permanent) {
  }
  virtual ~Callback2() {
  }
  void Run(X0 x0, X1 x1) {
    const bool permanent = is_permanent();
    RunInternal(x0, x1);
    if ( !permanent ) {
      delete this;
    }
  }
  bool is_permanent() const { return is_permanent_; }
protected:
  virtual void RunInternal(X0 x0, X1 x1) = 0;
private:
  const bool is_permanent_;
};

//////////////////////////////////////////////////////////////////////

template<typename X0, typename X1>
class Callback2_0 : public Callback2<X0, X1> {
public:
  typedef void (*Fun)(X0, X1);
  Callback2_0(bool is_permanent, Fun fun)
    : Callback2<X0, X1>(is_permanent),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
    (*fun_)(x0, x1);
  }
private:
  Fun fun_;
};
template<typename X0, typename X1>
Callback2_0<X0, X1>* NewCallback(void (*fun)(X0, X1)) {
  return new Callback2_0<X0, X1>(false, fun);
}
template<typename X0, typename X1>
Callback2_0<X0, X1>* NewPermanentCallback(void (*fun)(X0, X1)) {
  return new Callback2_0<X0, X1>(true, fun);
}

template<typename C, typename X0, typename X1>
class MemberCallback2_0 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(X0, X1);
  MemberCallback2_0 (bool is_permanent, C* c, Fun fun)
    : Callback2<X0, X1>(is_permanent),
      c_(c),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
    (c_->*fun_)(x0, x1);
  }
private:
  C* c_;
  Fun fun_;
};

template<typename C, typename X0, typename X1>
MemberCallback2_0<C, X0, X1>* NewCallback(C* c, void (C::*fun)(X0, X1)) {
  return new MemberCallback2_0<C, X0, X1>(false, c, fun);
}
template<typename C, typename X0, typename X1>
MemberCallback2_0<C, X0, X1>* NewPermanentCallback(C* c, void (C::*fun)(X0, X1)) {
  return new MemberCallback2_0<C, X0, X1>(true, c, fun);
}

template<typename C, typename X0, typename X1>
class ConstMemberCallback2_0 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(X0, X1) const;
  ConstMemberCallback2_0 (bool is_permanent, const C* c, Fun fun)
    : Callback2<X0, X1>(is_permanent),
      c_(c),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
    (c_->*fun_)(x0, x1);
  }
private:
  const C* c_;
  Fun fun_;
};

template<typename C, typename X0, typename X1>
ConstMemberCallback2_0<C, X0, X1>* NewCallback(const C* c, void (C::*fun)(X0, X1) const) {
  return new ConstMemberCallback2_0<C, X0, X1>(false, c, fun);
}
template<typename C, typename X0, typename X1>
ConstMemberCallback2_0<C, X0, X1>* NewPermanentCallback(const C* c, void (C::*fun)(X0, X1) const) {
  return new ConstMemberCallback2_0<C, X0, X1>(true, c, fun);
}

//////////////////////////////////////////////////////////////////////
//
// Autogenerated callback classes (w/ print_callback.py)
//

template<typename T0, typename X0, typename X1>
class Callback2_1 : public Callback2<X0, X1> {
public:
  typedef void (*Fun)(T0, X0, X1);
  Callback2_1(bool is_permanent, Fun fun, T0 p0)
    : Callback2<X0, X1>(is_permanent),
    p0_(p0),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
    (*fun_)(p0_, x0, x1);
  }
private:
  T0 p0_;
  Fun fun_;
};
template<typename T0, typename X0, typename X1>
Callback2_1<T0, X0, X1>* NewCallback(void (*fun)(T0, X0, X1), T0 p0) {
  return new Callback2_1<T0, X0, X1>(false, fun, p0);
}
template<typename T0, typename X0, typename X1>
Callback2_1<T0, X0, X1>* NewPermanentCallback(void (*fun)(T0, X0, X1), T0 p0) {
  return new Callback2_1<T0, X0, X1>(true, fun, p0);
}


template<typename C, typename T0, typename X0, typename X1>
class ConstMemberCallback2_1 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(T0, X0, X1) const;
  ConstMemberCallback2_1 (bool is_permanent, const C* c, Fun fun, T0 p0)
    : Callback2<X0, X1>(is_permanent),
    c_(c),
    p0_(p0),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
      (c_->*fun_)(p0_, x0, x1);
  }
private:
  const C* c_;
  T0 p0_;
  Fun fun_;
};

template<typename C, typename T0, typename X0, typename X1>
ConstMemberCallback2_1<C, T0, X0, X1>* NewCallback(const C* c, void (C::*fun)(T0, X0, X1) const, T0 p0) {
  return new ConstMemberCallback2_1<C, T0, X0, X1>(false, c, fun, p0);
}
template<typename C, typename T0, typename X0, typename X1>
ConstMemberCallback2_1<C, T0, X0, X1>* NewPermanentCallback(const C* c, void (C::*fun)(T0, X0, X1) const, T0 p0) {
  return new ConstMemberCallback2_1<C, T0, X0, X1>(true, c, fun, p0);
}



template<typename C, typename T0, typename X0, typename X1>
class MemberCallback2_1 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(T0, X0, X1);
  MemberCallback2_1 (bool is_permanent, C* c, Fun fun, T0 p0)
    : Callback2<X0, X1>(is_permanent),
    c_(c),
    p0_(p0),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
      (c_->*fun_)(p0_, x0, x1);
  }
private:
  C* c_;
  T0 p0_;
  Fun fun_;
};

template<typename C, typename T0, typename X0, typename X1>
MemberCallback2_1<C, T0, X0, X1>* NewCallback(C* c, void (C::*fun)(T0, X0, X1), T0 p0) {
  return new MemberCallback2_1<C, T0, X0, X1>(false, c, fun, p0);
}
template<typename C, typename T0, typename X0, typename X1>
MemberCallback2_1<C, T0, X0, X1>* NewPermanentCallback(C* c, void (C::*fun)(T0, X0, X1), T0 p0) {
  return new MemberCallback2_1<C, T0, X0, X1>(true, c, fun, p0);
}



template<typename T0, typename T1, typename X0, typename X1>
class Callback2_2 : public Callback2<X0, X1> {
public:
  typedef void (*Fun)(T0, T1, X0, X1);
  Callback2_2(bool is_permanent, Fun fun, T0 p0, T1 p1)
    : Callback2<X0, X1>(is_permanent),
    p0_(p0),
p1_(p1),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
    (*fun_)(p0_, p1_, x0, x1);
  }
private:
  T0 p0_;
T1 p1_;
  Fun fun_;
};
template<typename T0, typename T1, typename X0, typename X1>
Callback2_2<T0, T1, X0, X1>* NewCallback(void (*fun)(T0, T1, X0, X1), T0 p0, T1 p1) {
  return new Callback2_2<T0, T1, X0, X1>(false, fun, p0, p1);
}
template<typename T0, typename T1, typename X0, typename X1>
Callback2_2<T0, T1, X0, X1>* NewPermanentCallback(void (*fun)(T0, T1, X0, X1), T0 p0, T1 p1) {
  return new Callback2_2<T0, T1, X0, X1>(true, fun, p0, p1);
}


template<typename C, typename T0, typename T1, typename X0, typename X1>
class ConstMemberCallback2_2 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(T0, T1, X0, X1) const;
  ConstMemberCallback2_2 (bool is_permanent, const C* c, Fun fun, T0 p0, T1 p1)
    : Callback2<X0, X1>(is_permanent),
    c_(c),
    p0_(p0),
p1_(p1),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
      (c_->*fun_)(p0_, p1_, x0, x1);
  }
private:
  const C* c_;
  T0 p0_;
T1 p1_;
  Fun fun_;
};

template<typename C, typename T0, typename T1, typename X0, typename X1>
ConstMemberCallback2_2<C, T0, T1, X0, X1>* NewCallback(const C* c, void (C::*fun)(T0, T1, X0, X1) const, T0 p0, T1 p1) {
  return new ConstMemberCallback2_2<C, T0, T1, X0, X1>(false, c, fun, p0, p1);
}
template<typename C, typename T0, typename T1, typename X0, typename X1>
ConstMemberCallback2_2<C, T0, T1, X0, X1>* NewPermanentCallback(const C* c, void (C::*fun)(T0, T1, X0, X1) const, T0 p0, T1 p1) {
  return new ConstMemberCallback2_2<C, T0, T1, X0, X1>(true, c, fun, p0, p1);
}



template<typename C, typename T0, typename T1, typename X0, typename X1>
class MemberCallback2_2 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(T0, T1, X0, X1);
  MemberCallback2_2 (bool is_permanent, C* c, Fun fun, T0 p0, T1 p1)
    : Callback2<X0, X1>(is_permanent),
    c_(c),
    p0_(p0),
p1_(p1),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
      (c_->*fun_)(p0_, p1_, x0, x1);
  }
private:
  C* c_;
  T0 p0_;
T1 p1_;
  Fun fun_;
};

template<typename C, typename T0, typename T1, typename X0, typename X1>
MemberCallback2_2<C, T0, T1, X0, X1>* NewCallback(C* c, void (C::*fun)(T0, T1, X0, X1), T0 p0, T1 p1) {
  return new MemberCallback2_2<C, T0, T1, X0, X1>(false, c, fun, p0, p1);
}
template<typename C, typename T0, typename T1, typename X0, typename X1>
MemberCallback2_2<C, T0, T1, X0, X1>* NewPermanentCallback(C* c, void (C::*fun)(T0, T1, X0, X1), T0 p0, T1 p1) {
  return new MemberCallback2_2<C, T0, T1, X0, X1>(true, c, fun, p0, p1);
}



template<typename T0, typename T1, typename T2, typename X0, typename X1>
class Callback2_3 : public Callback2<X0, X1> {
public:
  typedef void (*Fun)(T0, T1, T2, X0, X1);
  Callback2_3(bool is_permanent, Fun fun, T0 p0, T1 p1, T2 p2)
    : Callback2<X0, X1>(is_permanent),
    p0_(p0),
p1_(p1),
p2_(p2),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
    (*fun_)(p0_, p1_, p2_, x0, x1);
  }
private:
  T0 p0_;
T1 p1_;
T2 p2_;
  Fun fun_;
};
template<typename T0, typename T1, typename T2, typename X0, typename X1>
Callback2_3<T0, T1, T2, X0, X1>* NewCallback(void (*fun)(T0, T1, T2, X0, X1), T0 p0, T1 p1, T2 p2) {
  return new Callback2_3<T0, T1, T2, X0, X1>(false, fun, p0, p1, p2);
}
template<typename T0, typename T1, typename T2, typename X0, typename X1>
Callback2_3<T0, T1, T2, X0, X1>* NewPermanentCallback(void (*fun)(T0, T1, T2, X0, X1), T0 p0, T1 p1, T2 p2) {
  return new Callback2_3<T0, T1, T2, X0, X1>(true, fun, p0, p1, p2);
}


template<typename C, typename T0, typename T1, typename T2, typename X0, typename X1>
class ConstMemberCallback2_3 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(T0, T1, T2, X0, X1) const;
  ConstMemberCallback2_3 (bool is_permanent, const C* c, Fun fun, T0 p0, T1 p1, T2 p2)
    : Callback2<X0, X1>(is_permanent),
    c_(c),
    p0_(p0),
p1_(p1),
p2_(p2),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
      (c_->*fun_)(p0_, p1_, p2_, x0, x1);
  }
private:
  const C* c_;
  T0 p0_;
T1 p1_;
T2 p2_;
  Fun fun_;
};

template<typename C, typename T0, typename T1, typename T2, typename X0, typename X1>
ConstMemberCallback2_3<C, T0, T1, T2, X0, X1>* NewCallback(const C* c, void (C::*fun)(T0, T1, T2, X0, X1) const, T0 p0, T1 p1, T2 p2) {
  return new ConstMemberCallback2_3<C, T0, T1, T2, X0, X1>(false, c, fun, p0, p1, p2);
}
template<typename C, typename T0, typename T1, typename T2, typename X0, typename X1>
ConstMemberCallback2_3<C, T0, T1, T2, X0, X1>* NewPermanentCallback(const C* c, void (C::*fun)(T0, T1, T2, X0, X1) const, T0 p0, T1 p1, T2 p2) {
  return new ConstMemberCallback2_3<C, T0, T1, T2, X0, X1>(true, c, fun, p0, p1, p2);
}



template<typename C, typename T0, typename T1, typename T2, typename X0, typename X1>
class MemberCallback2_3 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(T0, T1, T2, X0, X1);
  MemberCallback2_3 (bool is_permanent, C* c, Fun fun, T0 p0, T1 p1, T2 p2)
    : Callback2<X0, X1>(is_permanent),
    c_(c),
    p0_(p0),
p1_(p1),
p2_(p2),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
      (c_->*fun_)(p0_, p1_, p2_, x0, x1);
  }
private:
  C* c_;
  T0 p0_;
T1 p1_;
T2 p2_;
  Fun fun_;
};

template<typename C, typename T0, typename T1, typename T2, typename X0, typename X1>
MemberCallback2_3<C, T0, T1, T2, X0, X1>* NewCallback(C* c, void (C::*fun)(T0, T1, T2, X0, X1), T0 p0, T1 p1, T2 p2) {
  return new MemberCallback2_3<C, T0, T1, T2, X0, X1>(false, c, fun, p0, p1, p2);
}
template<typename C, typename T0, typename T1, typename T2, typename X0, typename X1>
MemberCallback2_3<C, T0, T1, T2, X0, X1>* NewPermanentCallback(C* c, void (C::*fun)(T0, T1, T2, X0, X1), T0 p0, T1 p1, T2 p2) {
  return new MemberCallback2_3<C, T0, T1, T2, X0, X1>(true, c, fun, p0, p1, p2);
}



template<typename T0, typename T1, typename T2, typename T3, typename X0, typename X1>
class Callback2_4 : public Callback2<X0, X1> {
public:
  typedef void (*Fun)(T0, T1, T2, T3, X0, X1);
  Callback2_4(bool is_permanent, Fun fun, T0 p0, T1 p1, T2 p2, T3 p3)
    : Callback2<X0, X1>(is_permanent),
    p0_(p0),
p1_(p1),
p2_(p2),
p3_(p3),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
    (*fun_)(p0_, p1_, p2_, p3_, x0, x1);
  }
private:
  T0 p0_;
T1 p1_;
T2 p2_;
T3 p3_;
  Fun fun_;
};
template<typename T0, typename T1, typename T2, typename T3, typename X0, typename X1>
Callback2_4<T0, T1, T2, T3, X0, X1>* NewCallback(void (*fun)(T0, T1, T2, T3, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3) {
  return new Callback2_4<T0, T1, T2, T3, X0, X1>(false, fun, p0, p1, p2, p3);
}
template<typename T0, typename T1, typename T2, typename T3, typename X0, typename X1>
Callback2_4<T0, T1, T2, T3, X0, X1>* NewPermanentCallback(void (*fun)(T0, T1, T2, T3, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3) {
  return new Callback2_4<T0, T1, T2, T3, X0, X1>(true, fun, p0, p1, p2, p3);
}


template<typename C, typename T0, typename T1, typename T2, typename T3, typename X0, typename X1>
class ConstMemberCallback2_4 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(T0, T1, T2, T3, X0, X1) const;
  ConstMemberCallback2_4 (bool is_permanent, const C* c, Fun fun, T0 p0, T1 p1, T2 p2, T3 p3)
    : Callback2<X0, X1>(is_permanent),
    c_(c),
    p0_(p0),
p1_(p1),
p2_(p2),
p3_(p3),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
      (c_->*fun_)(p0_, p1_, p2_, p3_, x0, x1);
  }
private:
  const C* c_;
  T0 p0_;
T1 p1_;
T2 p2_;
T3 p3_;
  Fun fun_;
};

template<typename C, typename T0, typename T1, typename T2, typename T3, typename X0, typename X1>
ConstMemberCallback2_4<C, T0, T1, T2, T3, X0, X1>* NewCallback(const C* c, void (C::*fun)(T0, T1, T2, T3, X0, X1) const, T0 p0, T1 p1, T2 p2, T3 p3) {
  return new ConstMemberCallback2_4<C, T0, T1, T2, T3, X0, X1>(false, c, fun, p0, p1, p2, p3);
}
template<typename C, typename T0, typename T1, typename T2, typename T3, typename X0, typename X1>
ConstMemberCallback2_4<C, T0, T1, T2, T3, X0, X1>* NewPermanentCallback(const C* c, void (C::*fun)(T0, T1, T2, T3, X0, X1) const, T0 p0, T1 p1, T2 p2, T3 p3) {
  return new ConstMemberCallback2_4<C, T0, T1, T2, T3, X0, X1>(true, c, fun, p0, p1, p2, p3);
}



template<typename C, typename T0, typename T1, typename T2, typename T3, typename X0, typename X1>
class MemberCallback2_4 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(T0, T1, T2, T3, X0, X1);
  MemberCallback2_4 (bool is_permanent, C* c, Fun fun, T0 p0, T1 p1, T2 p2, T3 p3)
    : Callback2<X0, X1>(is_permanent),
    c_(c),
    p0_(p0),
p1_(p1),
p2_(p2),
p3_(p3),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
      (c_->*fun_)(p0_, p1_, p2_, p3_, x0, x1);
  }
private:
  C* c_;
  T0 p0_;
T1 p1_;
T2 p2_;
T3 p3_;
  Fun fun_;
};

template<typename C, typename T0, typename T1, typename T2, typename T3, typename X0, typename X1>
MemberCallback2_4<C, T0, T1, T2, T3, X0, X1>* NewCallback(C* c, void (C::*fun)(T0, T1, T2, T3, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3) {
  return new MemberCallback2_4<C, T0, T1, T2, T3, X0, X1>(false, c, fun, p0, p1, p2, p3);
}
template<typename C, typename T0, typename T1, typename T2, typename T3, typename X0, typename X1>
MemberCallback2_4<C, T0, T1, T2, T3, X0, X1>* NewPermanentCallback(C* c, void (C::*fun)(T0, T1, T2, T3, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3) {
  return new MemberCallback2_4<C, T0, T1, T2, T3, X0, X1>(true, c, fun, p0, p1, p2, p3);
}



template<typename T0, typename T1, typename T2, typename T3, typename T4, typename X0, typename X1>
class Callback2_5 : public Callback2<X0, X1> {
public:
  typedef void (*Fun)(T0, T1, T2, T3, T4, X0, X1);
  Callback2_5(bool is_permanent, Fun fun, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4)
    : Callback2<X0, X1>(is_permanent),
    p0_(p0),
p1_(p1),
p2_(p2),
p3_(p3),
p4_(p4),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
    (*fun_)(p0_, p1_, p2_, p3_, p4_, x0, x1);
  }
private:
  T0 p0_;
T1 p1_;
T2 p2_;
T3 p3_;
T4 p4_;
  Fun fun_;
};
template<typename T0, typename T1, typename T2, typename T3, typename T4, typename X0, typename X1>
Callback2_5<T0, T1, T2, T3, T4, X0, X1>* NewCallback(void (*fun)(T0, T1, T2, T3, T4, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4) {
  return new Callback2_5<T0, T1, T2, T3, T4, X0, X1>(false, fun, p0, p1, p2, p3, p4);
}
template<typename T0, typename T1, typename T2, typename T3, typename T4, typename X0, typename X1>
Callback2_5<T0, T1, T2, T3, T4, X0, X1>* NewPermanentCallback(void (*fun)(T0, T1, T2, T3, T4, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4) {
  return new Callback2_5<T0, T1, T2, T3, T4, X0, X1>(true, fun, p0, p1, p2, p3, p4);
}


template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename X0, typename X1>
class ConstMemberCallback2_5 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(T0, T1, T2, T3, T4, X0, X1) const;
  ConstMemberCallback2_5 (bool is_permanent, const C* c, Fun fun, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4)
    : Callback2<X0, X1>(is_permanent),
    c_(c),
    p0_(p0),
p1_(p1),
p2_(p2),
p3_(p3),
p4_(p4),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
      (c_->*fun_)(p0_, p1_, p2_, p3_, p4_, x0, x1);
  }
private:
  const C* c_;
  T0 p0_;
T1 p1_;
T2 p2_;
T3 p3_;
T4 p4_;
  Fun fun_;
};

template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename X0, typename X1>
ConstMemberCallback2_5<C, T0, T1, T2, T3, T4, X0, X1>* NewCallback(const C* c, void (C::*fun)(T0, T1, T2, T3, T4, X0, X1) const, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4) {
  return new ConstMemberCallback2_5<C, T0, T1, T2, T3, T4, X0, X1>(false, c, fun, p0, p1, p2, p3, p4);
}
template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename X0, typename X1>
ConstMemberCallback2_5<C, T0, T1, T2, T3, T4, X0, X1>* NewPermanentCallback(const C* c, void (C::*fun)(T0, T1, T2, T3, T4, X0, X1) const, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4) {
  return new ConstMemberCallback2_5<C, T0, T1, T2, T3, T4, X0, X1>(true, c, fun, p0, p1, p2, p3, p4);
}



template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename X0, typename X1>
class MemberCallback2_5 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(T0, T1, T2, T3, T4, X0, X1);
  MemberCallback2_5 (bool is_permanent, C* c, Fun fun, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4)
    : Callback2<X0, X1>(is_permanent),
    c_(c),
    p0_(p0),
p1_(p1),
p2_(p2),
p3_(p3),
p4_(p4),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
      (c_->*fun_)(p0_, p1_, p2_, p3_, p4_, x0, x1);
  }
private:
  C* c_;
  T0 p0_;
T1 p1_;
T2 p2_;
T3 p3_;
T4 p4_;
  Fun fun_;
};

template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename X0, typename X1>
MemberCallback2_5<C, T0, T1, T2, T3, T4, X0, X1>* NewCallback(C* c, void (C::*fun)(T0, T1, T2, T3, T4, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4) {
  return new MemberCallback2_5<C, T0, T1, T2, T3, T4, X0, X1>(false, c, fun, p0, p1, p2, p3, p4);
}
template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename X0, typename X1>
MemberCallback2_5<C, T0, T1, T2, T3, T4, X0, X1>* NewPermanentCallback(C* c, void (C::*fun)(T0, T1, T2, T3, T4, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4) {
  return new MemberCallback2_5<C, T0, T1, T2, T3, T4, X0, X1>(true, c, fun, p0, p1, p2, p3, p4);
}



template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename X0, typename X1>
class Callback2_6 : public Callback2<X0, X1> {
public:
  typedef void (*Fun)(T0, T1, T2, T3, T4, T5, X0, X1);
  Callback2_6(bool is_permanent, Fun fun, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5)
    : Callback2<X0, X1>(is_permanent),
    p0_(p0),
p1_(p1),
p2_(p2),
p3_(p3),
p4_(p4),
p5_(p5),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
    (*fun_)(p0_, p1_, p2_, p3_, p4_, p5_, x0, x1);
  }
private:
  T0 p0_;
T1 p1_;
T2 p2_;
T3 p3_;
T4 p4_;
T5 p5_;
  Fun fun_;
};
template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename X0, typename X1>
Callback2_6<T0, T1, T2, T3, T4, T5, X0, X1>* NewCallback(void (*fun)(T0, T1, T2, T3, T4, T5, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5) {
  return new Callback2_6<T0, T1, T2, T3, T4, T5, X0, X1>(false, fun, p0, p1, p2, p3, p4, p5);
}
template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename X0, typename X1>
Callback2_6<T0, T1, T2, T3, T4, T5, X0, X1>* NewPermanentCallback(void (*fun)(T0, T1, T2, T3, T4, T5, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5) {
  return new Callback2_6<T0, T1, T2, T3, T4, T5, X0, X1>(true, fun, p0, p1, p2, p3, p4, p5);
}


template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename X0, typename X1>
class ConstMemberCallback2_6 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(T0, T1, T2, T3, T4, T5, X0, X1) const;
  ConstMemberCallback2_6 (bool is_permanent, const C* c, Fun fun, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5)
    : Callback2<X0, X1>(is_permanent),
    c_(c),
    p0_(p0),
p1_(p1),
p2_(p2),
p3_(p3),
p4_(p4),
p5_(p5),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
      (c_->*fun_)(p0_, p1_, p2_, p3_, p4_, p5_, x0, x1);
  }
private:
  const C* c_;
  T0 p0_;
T1 p1_;
T2 p2_;
T3 p3_;
T4 p4_;
T5 p5_;
  Fun fun_;
};

template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename X0, typename X1>
ConstMemberCallback2_6<C, T0, T1, T2, T3, T4, T5, X0, X1>* NewCallback(const C* c, void (C::*fun)(T0, T1, T2, T3, T4, T5, X0, X1) const, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5) {
  return new ConstMemberCallback2_6<C, T0, T1, T2, T3, T4, T5, X0, X1>(false, c, fun, p0, p1, p2, p3, p4, p5);
}
template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename X0, typename X1>
ConstMemberCallback2_6<C, T0, T1, T2, T3, T4, T5, X0, X1>* NewPermanentCallback(const C* c, void (C::*fun)(T0, T1, T2, T3, T4, T5, X0, X1) const, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5) {
  return new ConstMemberCallback2_6<C, T0, T1, T2, T3, T4, T5, X0, X1>(true, c, fun, p0, p1, p2, p3, p4, p5);
}



template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename X0, typename X1>
class MemberCallback2_6 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(T0, T1, T2, T3, T4, T5, X0, X1);
  MemberCallback2_6 (bool is_permanent, C* c, Fun fun, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5)
    : Callback2<X0, X1>(is_permanent),
    c_(c),
    p0_(p0),
p1_(p1),
p2_(p2),
p3_(p3),
p4_(p4),
p5_(p5),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
      (c_->*fun_)(p0_, p1_, p2_, p3_, p4_, p5_, x0, x1);
  }
private:
  C* c_;
  T0 p0_;
T1 p1_;
T2 p2_;
T3 p3_;
T4 p4_;
T5 p5_;
  Fun fun_;
};

template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename X0, typename X1>
MemberCallback2_6<C, T0, T1, T2, T3, T4, T5, X0, X1>* NewCallback(C* c, void (C::*fun)(T0, T1, T2, T3, T4, T5, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5) {
  return new MemberCallback2_6<C, T0, T1, T2, T3, T4, T5, X0, X1>(false, c, fun, p0, p1, p2, p3, p4, p5);
}
template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename X0, typename X1>
MemberCallback2_6<C, T0, T1, T2, T3, T4, T5, X0, X1>* NewPermanentCallback(C* c, void (C::*fun)(T0, T1, T2, T3, T4, T5, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5) {
  return new MemberCallback2_6<C, T0, T1, T2, T3, T4, T5, X0, X1>(true, c, fun, p0, p1, p2, p3, p4, p5);
}



template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename X0, typename X1>
class Callback2_7 : public Callback2<X0, X1> {
public:
  typedef void (*Fun)(T0, T1, T2, T3, T4, T5, T6, X0, X1);
  Callback2_7(bool is_permanent, Fun fun, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6)
    : Callback2<X0, X1>(is_permanent),
    p0_(p0),
p1_(p1),
p2_(p2),
p3_(p3),
p4_(p4),
p5_(p5),
p6_(p6),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
    (*fun_)(p0_, p1_, p2_, p3_, p4_, p5_, p6_, x0, x1);
  }
private:
  T0 p0_;
T1 p1_;
T2 p2_;
T3 p3_;
T4 p4_;
T5 p5_;
T6 p6_;
  Fun fun_;
};
template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename X0, typename X1>
Callback2_7<T0, T1, T2, T3, T4, T5, T6, X0, X1>* NewCallback(void (*fun)(T0, T1, T2, T3, T4, T5, T6, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6) {
  return new Callback2_7<T0, T1, T2, T3, T4, T5, T6, X0, X1>(false, fun, p0, p1, p2, p3, p4, p5, p6);
}
template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename X0, typename X1>
Callback2_7<T0, T1, T2, T3, T4, T5, T6, X0, X1>* NewPermanentCallback(void (*fun)(T0, T1, T2, T3, T4, T5, T6, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6) {
  return new Callback2_7<T0, T1, T2, T3, T4, T5, T6, X0, X1>(true, fun, p0, p1, p2, p3, p4, p5, p6);
}


template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename X0, typename X1>
class ConstMemberCallback2_7 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(T0, T1, T2, T3, T4, T5, T6, X0, X1) const;
  ConstMemberCallback2_7 (bool is_permanent, const C* c, Fun fun, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6)
    : Callback2<X0, X1>(is_permanent),
    c_(c),
    p0_(p0),
p1_(p1),
p2_(p2),
p3_(p3),
p4_(p4),
p5_(p5),
p6_(p6),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
      (c_->*fun_)(p0_, p1_, p2_, p3_, p4_, p5_, p6_, x0, x1);
  }
private:
  const C* c_;
  T0 p0_;
T1 p1_;
T2 p2_;
T3 p3_;
T4 p4_;
T5 p5_;
T6 p6_;
  Fun fun_;
};

template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename X0, typename X1>
ConstMemberCallback2_7<C, T0, T1, T2, T3, T4, T5, T6, X0, X1>* NewCallback(const C* c, void (C::*fun)(T0, T1, T2, T3, T4, T5, T6, X0, X1) const, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6) {
  return new ConstMemberCallback2_7<C, T0, T1, T2, T3, T4, T5, T6, X0, X1>(false, c, fun, p0, p1, p2, p3, p4, p5, p6);
}
template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename X0, typename X1>
ConstMemberCallback2_7<C, T0, T1, T2, T3, T4, T5, T6, X0, X1>* NewPermanentCallback(const C* c, void (C::*fun)(T0, T1, T2, T3, T4, T5, T6, X0, X1) const, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6) {
  return new ConstMemberCallback2_7<C, T0, T1, T2, T3, T4, T5, T6, X0, X1>(true, c, fun, p0, p1, p2, p3, p4, p5, p6);
}



template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename X0, typename X1>
class MemberCallback2_7 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(T0, T1, T2, T3, T4, T5, T6, X0, X1);
  MemberCallback2_7 (bool is_permanent, C* c, Fun fun, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6)
    : Callback2<X0, X1>(is_permanent),
    c_(c),
    p0_(p0),
p1_(p1),
p2_(p2),
p3_(p3),
p4_(p4),
p5_(p5),
p6_(p6),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
      (c_->*fun_)(p0_, p1_, p2_, p3_, p4_, p5_, p6_, x0, x1);
  }
private:
  C* c_;
  T0 p0_;
T1 p1_;
T2 p2_;
T3 p3_;
T4 p4_;
T5 p5_;
T6 p6_;
  Fun fun_;
};

template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename X0, typename X1>
MemberCallback2_7<C, T0, T1, T2, T3, T4, T5, T6, X0, X1>* NewCallback(C* c, void (C::*fun)(T0, T1, T2, T3, T4, T5, T6, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6) {
  return new MemberCallback2_7<C, T0, T1, T2, T3, T4, T5, T6, X0, X1>(false, c, fun, p0, p1, p2, p3, p4, p5, p6);
}
template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename X0, typename X1>
MemberCallback2_7<C, T0, T1, T2, T3, T4, T5, T6, X0, X1>* NewPermanentCallback(C* c, void (C::*fun)(T0, T1, T2, T3, T4, T5, T6, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6) {
  return new MemberCallback2_7<C, T0, T1, T2, T3, T4, T5, T6, X0, X1>(true, c, fun, p0, p1, p2, p3, p4, p5, p6);
}



template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename X0, typename X1>
class Callback2_8 : public Callback2<X0, X1> {
public:
  typedef void (*Fun)(T0, T1, T2, T3, T4, T5, T6, T7, X0, X1);
  Callback2_8(bool is_permanent, Fun fun, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7)
    : Callback2<X0, X1>(is_permanent),
    p0_(p0),
p1_(p1),
p2_(p2),
p3_(p3),
p4_(p4),
p5_(p5),
p6_(p6),
p7_(p7),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
    (*fun_)(p0_, p1_, p2_, p3_, p4_, p5_, p6_, p7_, x0, x1);
  }
private:
  T0 p0_;
T1 p1_;
T2 p2_;
T3 p3_;
T4 p4_;
T5 p5_;
T6 p6_;
T7 p7_;
  Fun fun_;
};
template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename X0, typename X1>
Callback2_8<T0, T1, T2, T3, T4, T5, T6, T7, X0, X1>* NewCallback(void (*fun)(T0, T1, T2, T3, T4, T5, T6, T7, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7) {
  return new Callback2_8<T0, T1, T2, T3, T4, T5, T6, T7, X0, X1>(false, fun, p0, p1, p2, p3, p4, p5, p6, p7);
}
template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename X0, typename X1>
Callback2_8<T0, T1, T2, T3, T4, T5, T6, T7, X0, X1>* NewPermanentCallback(void (*fun)(T0, T1, T2, T3, T4, T5, T6, T7, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7) {
  return new Callback2_8<T0, T1, T2, T3, T4, T5, T6, T7, X0, X1>(true, fun, p0, p1, p2, p3, p4, p5, p6, p7);
}


template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename X0, typename X1>
class ConstMemberCallback2_8 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(T0, T1, T2, T3, T4, T5, T6, T7, X0, X1) const;
  ConstMemberCallback2_8 (bool is_permanent, const C* c, Fun fun, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7)
    : Callback2<X0, X1>(is_permanent),
    c_(c),
    p0_(p0),
p1_(p1),
p2_(p2),
p3_(p3),
p4_(p4),
p5_(p5),
p6_(p6),
p7_(p7),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
      (c_->*fun_)(p0_, p1_, p2_, p3_, p4_, p5_, p6_, p7_, x0, x1);
  }
private:
  const C* c_;
  T0 p0_;
T1 p1_;
T2 p2_;
T3 p3_;
T4 p4_;
T5 p5_;
T6 p6_;
T7 p7_;
  Fun fun_;
};

template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename X0, typename X1>
ConstMemberCallback2_8<C, T0, T1, T2, T3, T4, T5, T6, T7, X0, X1>* NewCallback(const C* c, void (C::*fun)(T0, T1, T2, T3, T4, T5, T6, T7, X0, X1) const, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7) {
  return new ConstMemberCallback2_8<C, T0, T1, T2, T3, T4, T5, T6, T7, X0, X1>(false, c, fun, p0, p1, p2, p3, p4, p5, p6, p7);
}
template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename X0, typename X1>
ConstMemberCallback2_8<C, T0, T1, T2, T3, T4, T5, T6, T7, X0, X1>* NewPermanentCallback(const C* c, void (C::*fun)(T0, T1, T2, T3, T4, T5, T6, T7, X0, X1) const, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7) {
  return new ConstMemberCallback2_8<C, T0, T1, T2, T3, T4, T5, T6, T7, X0, X1>(true, c, fun, p0, p1, p2, p3, p4, p5, p6, p7);
}



template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename X0, typename X1>
class MemberCallback2_8 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(T0, T1, T2, T3, T4, T5, T6, T7, X0, X1);
  MemberCallback2_8 (bool is_permanent, C* c, Fun fun, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7)
    : Callback2<X0, X1>(is_permanent),
    c_(c),
    p0_(p0),
p1_(p1),
p2_(p2),
p3_(p3),
p4_(p4),
p5_(p5),
p6_(p6),
p7_(p7),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
      (c_->*fun_)(p0_, p1_, p2_, p3_, p4_, p5_, p6_, p7_, x0, x1);
  }
private:
  C* c_;
  T0 p0_;
T1 p1_;
T2 p2_;
T3 p3_;
T4 p4_;
T5 p5_;
T6 p6_;
T7 p7_;
  Fun fun_;
};

template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename X0, typename X1>
MemberCallback2_8<C, T0, T1, T2, T3, T4, T5, T6, T7, X0, X1>* NewCallback(C* c, void (C::*fun)(T0, T1, T2, T3, T4, T5, T6, T7, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7) {
  return new MemberCallback2_8<C, T0, T1, T2, T3, T4, T5, T6, T7, X0, X1>(false, c, fun, p0, p1, p2, p3, p4, p5, p6, p7);
}
template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename X0, typename X1>
MemberCallback2_8<C, T0, T1, T2, T3, T4, T5, T6, T7, X0, X1>* NewPermanentCallback(C* c, void (C::*fun)(T0, T1, T2, T3, T4, T5, T6, T7, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7) {
  return new MemberCallback2_8<C, T0, T1, T2, T3, T4, T5, T6, T7, X0, X1>(true, c, fun, p0, p1, p2, p3, p4, p5, p6, p7);
}



template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename X0, typename X1>
class Callback2_9 : public Callback2<X0, X1> {
public:
  typedef void (*Fun)(T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1);
  Callback2_9(bool is_permanent, Fun fun, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8)
    : Callback2<X0, X1>(is_permanent),
    p0_(p0),
p1_(p1),
p2_(p2),
p3_(p3),
p4_(p4),
p5_(p5),
p6_(p6),
p7_(p7),
p8_(p8),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
    (*fun_)(p0_, p1_, p2_, p3_, p4_, p5_, p6_, p7_, p8_, x0, x1);
  }
private:
  T0 p0_;
T1 p1_;
T2 p2_;
T3 p3_;
T4 p4_;
T5 p5_;
T6 p6_;
T7 p7_;
T8 p8_;
  Fun fun_;
};
template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename X0, typename X1>
Callback2_9<T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1>* NewCallback(void (*fun)(T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8) {
  return new Callback2_9<T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1>(false, fun, p0, p1, p2, p3, p4, p5, p6, p7, p8);
}
template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename X0, typename X1>
Callback2_9<T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1>* NewPermanentCallback(void (*fun)(T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8) {
  return new Callback2_9<T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1>(true, fun, p0, p1, p2, p3, p4, p5, p6, p7, p8);
}


template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename X0, typename X1>
class ConstMemberCallback2_9 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1) const;
  ConstMemberCallback2_9 (bool is_permanent, const C* c, Fun fun, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8)
    : Callback2<X0, X1>(is_permanent),
    c_(c),
    p0_(p0),
p1_(p1),
p2_(p2),
p3_(p3),
p4_(p4),
p5_(p5),
p6_(p6),
p7_(p7),
p8_(p8),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
      (c_->*fun_)(p0_, p1_, p2_, p3_, p4_, p5_, p6_, p7_, p8_, x0, x1);
  }
private:
  const C* c_;
  T0 p0_;
T1 p1_;
T2 p2_;
T3 p3_;
T4 p4_;
T5 p5_;
T6 p6_;
T7 p7_;
T8 p8_;
  Fun fun_;
};

template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename X0, typename X1>
ConstMemberCallback2_9<C, T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1>* NewCallback(const C* c, void (C::*fun)(T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1) const, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8) {
  return new ConstMemberCallback2_9<C, T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1>(false, c, fun, p0, p1, p2, p3, p4, p5, p6, p7, p8);
}
template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename X0, typename X1>
ConstMemberCallback2_9<C, T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1>* NewPermanentCallback(const C* c, void (C::*fun)(T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1) const, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8) {
  return new ConstMemberCallback2_9<C, T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1>(true, c, fun, p0, p1, p2, p3, p4, p5, p6, p7, p8);
}



template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename X0, typename X1>
class MemberCallback2_9 : public Callback2<X0, X1> {
public:
  typedef void (C::*Fun)(T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1);
  MemberCallback2_9 (bool is_permanent, C* c, Fun fun, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8)
    : Callback2<X0, X1>(is_permanent),
    c_(c),
    p0_(p0),
p1_(p1),
p2_(p2),
p3_(p3),
p4_(p4),
p5_(p5),
p6_(p6),
p7_(p7),
p8_(p8),
      fun_(fun) {
  }
protected:
  virtual void RunInternal(X0 x0, X1 x1) {
      (c_->*fun_)(p0_, p1_, p2_, p3_, p4_, p5_, p6_, p7_, p8_, x0, x1);
  }
private:
  C* c_;
  T0 p0_;
T1 p1_;
T2 p2_;
T3 p3_;
T4 p4_;
T5 p5_;
T6 p6_;
T7 p7_;
T8 p8_;
  Fun fun_;
};

template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename X0, typename X1>
MemberCallback2_9<C, T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1>* NewCallback(C* c, void (C::*fun)(T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8) {
  return new MemberCallback2_9<C, T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1>(false, c, fun, p0, p1, p2, p3, p4, p5, p6, p7, p8);
}
template<typename C, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename X0, typename X1>
MemberCallback2_9<C, T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1>* NewPermanentCallback(C* c, void (C::*fun)(T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1), T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8) {
  return new MemberCallback2_9<C, T0, T1, T2, T3, T4, T5, T6, T7, T8, X0, X1>(true, c, fun, p0, p1, p2, p3, p4, p5, p6, p7, p8);
}

}

#endif   //  __WHISPERLIB_BASE_CALLBACK_CALLBACK2_H__
