# -*- Mode:python; indent-tabs-mode:nil; coding:utf-8 -*-

def build(ctx):
    source = ['errno.cc',
              'date.cc',
              'strutil.cc',
              'strutil_format.cc',
              'system.cc',
              're.cc',
              'timer.cc',
              'util.cc',
              ]
    if 'HAVE_REGEX_H' in ctx.env.DEFINES:
        source.append('re.cc')
    if not ctx.env.ANDROID and not ctx.env.IOS:
        source.append('app.cc')
    if not ctx.env.ANDROID:
        source.append('signal_handlers.cc')

    ctx.add_lib(ctx,
        toplib = 'whisperlib',
        name = 'whisperlib.base',
        target = 'whisperlib',
        source = source)
    ctx.install_all_includes(ctx)

    ctx.add_whisper_tests(ctx, [
            'strutil_test.cc',
            'lru_cache_test.cc',
            ])
