# -*- Mode:python; indent-tabs-mode:nil; coding:utf-8 -*-

HTTP_SERVER_SOURCES = [
    "http_server_protocol.cc",
]
HTTP_SOURCES = [
    "failsafe_http_client.cc",
    "http_client_protocol.cc",
    "http_consts.cc",
    "http_header.cc",
    "http_request.cc",
]

def build(ctx):
    sources = list(HTTP_SOURCES)
    if not ctx.env.IOS and not ctx.env.ANDROID:
        sources.extend(HTTP_SERVER_SOURCES)
    ctx.add_lib(
        ctx,
        toplib = 'whisperlib',
        name = 'whisperlib.http',
        target = 'whisperlib',
        source = sources)
    ctx.install_all_includes(ctx)

    ctx.add_whisper_tests(ctx, [
                   'failsafe_test.cc',
                   'http_get_page.cc',
                   'http_header_test.cc',
                   'http_request_test.cc',
                   ])
