# -*- Mode:python; indent-tabs-mode:nil; coding:utf-8 -*-

def build(ctx):
    if ctx.env.HAVE_ICU and not (ctx.env.ANDROID or ctx.env.IOS):
        ctx.add_lib(
            ctx,
            toplib = 'whisperlib',
            name = 'whisperlib.net',
            target = 'whisperlib',
            source = [
                'google-url/gurl.cc',
                'google-url/url_canon_etc.cc',
                'google-url/url_canon_fileurl.cc',
                'google-url/url_canon_host.cc',
                'google-url/url_canon_icu.cc',
                'google-url/url_canon_internal.cc',
                'google-url/url_canon_ip.cc',
                'google-url/url_canon_path.cc',
                'google-url/url_canon_pathurl.cc',
                'google-url/url_canon_query.cc',
                'google-url/url_canon_relative.cc',
                'google-url/url_canon_stdurl.cc',
                'google-url/url_parse.cc',
                'google-url/url_parse_file.cc',
                'google-url/url_util.cc',
                ])
        ctx.install_all_includes(ctx, max_depth=2)
    else:
        ctx.add_lib(
            ctx,
            toplib = 'whisperlib',
            name = 'whisperlib.net',
            target = 'whisperlib',
            source = [
                'simple_url.cc',
                ])
        ctx.install_all_includes(ctx, max_depth=1)
