# -*- Mode:python; indent-tabs-mode:nil; coding:utf-8 -*-

def build(ctx):
    ctx.add_lib(ctx,
        toplib = 'whisperlib',
        name = 'whisperlib.sync',
        target = 'whisperlib',
        source = ['thread.cc',
                  'thread_pool.cc',
                  'event.cc',
                  ])
    ctx.install_all_includes(ctx)
