# -*- Mode:python; indent-tabs-mode:nil; coding:utf-8 -*-

def build(ctx):
    sources = [
        'checkpointing.cc',
        'state_keeper.cc',
    ]
    ctx.add_lib(ctx,
        toplib = 'whisperlib',
        name = 'whisperlib.io.checkpoint',
        target = 'whisperlib',
        source = sources)
    ctx.add_whisper_tests(ctx, [
            'checkpointing_test.cc',
            'state_keeper_test.cc'])
    ctx.add_whisper_tests(ctx, [
            'checkpoint_tool.cc',
            'state_keeper_tool.cc'],
            prefix = '')
